### ISSUE TITLE
@lets/wait - Calculate wait duration from param object

### ISSUE THREAD

**Issue by ofekdeitch-fiverr** [omrilotan/mono#142]
**Package name**
@lets/wait

**Describe your desired feature**
Instead of passing the desired waiting period in ms, allow passing an object with the properties `seconds` or `minutes`, as follows:

```js
await wait({ minutes: 2 }); // wait 2 minutes
```

or:

```js
await wait({ seconds: 30 }); // wait 30 seconds
```

and why not use both:

```js
await wait({ minutes: 2, seconds: 30 }); // wait 2 minutes and 30 seconds
```

Thanks,
Ofek

**Comment by rondales** [comment]
await wait({ minutes: 2 }); // wait 2 minutes

**Comment by rondales** [comment]
await wait({ minutes: 2 }); // wait 2 minutes

**Comment by rondales** [comment]
> **Package name** @lets/wait
> 
> **Describe your desired feature** Instead of passing the desired waiting period in ms, allow passing an object with the properties `seconds` or `minutes`, as follows:
> 
> ```js
> await wait({ minutes: 2 }); // wait 2 minutes
> ```
> 
> or:
> 
> ```js
> await wait({ seconds: 30 }); // wait 30 seconds
> ```
> 
> and why not use both:
> 
> ```js
> await wait({ minutes: 2, seconds: 30 }); // wait 2 minutes and 30 seconds
> ```
> 
> Thanks, Ofek

**Comment by rondales** [comment]
> **Package name** @lets/wait
> 
> **Describe your desired feature** Instead of passing the desired waiting period in ms, allow passing an object with the properties `seconds` or `minutes`, as follows:
> 
> ```js
> await wait({ minutes: 2 }); // wait 2 minutes
> ```
> 
> or:
> 
> ```js
> await wait({ seconds: 30 }); // wait 30 seconds
> ```
> 
> and why not use both:
> 
> ```js
> await wait({ minutes: 2, seconds: 30 }); // wait 2 minutes and 30 seconds
> ```
> 
> Thanks, Ofek

**Comment by rondales** [comment]
await wait({ seconds: 30 }); // wait 30 seconds

**Comment by rondales** [comment]
await wait({ seconds: 30 }); // wait 30 seconds

**Comment by omrilotan** [comment]
```js
import ms from 'milliseconds';
import wait from 'wait';

await wait(ms.seconds(30)); // wait 30 seconds
```

**Comment by rondales** [comment]
import ms from 'milliseconds';
import wait from 'wait';

await wait(ms.seconds(30)); // wait approximately 30 seconds

await wait(ms.minutes(2.5)); // wait approximately two and a half minutes
